#!/bin/bash

xcomposer config --global discard-changes true

if [ -n "$GITHUB_TOKEN" ]; then
    echo "Configurando github..."
    mkdir -p ~/.ssh/
    touch ~/.ssh/known_hosts
    ssh-keyscan -t rsa github.com | tee ~/.ssh/known_hosts | ssh-keygen -lf -
    xcomposer config -g github-oauth.github.com ${GITHUB_TOKEN}
fi

if [ -n "$CODECOMMIT_USER" ]; then
    echo "Configurando codecommit..."
    xcomposer config -g http-basic.${CODECOMMIT_HOST} ${CODECOMMIT_USER} ${CODECOMMIT_PASSWORD}
fi
