#!/bin/bash

if [ ! -f auth.json ]; then
    sudo touch auth.json && sudo echo "{}" >> auth.json
fi

if [ ! -d vendor ]; then
    sudo mkdir vendor
fi

if [ -n "$GITHUB_TOKEN" ]; then
    echo "Configurando github..."
    sudo composer config github-oauth.github.com $GITHUB_TOKEN
fi

if [ -n "$CODECOMMIT_HOST" ]; then
    echo "Configurando codecommit..."
    sudo composer config http-basic.${CODECOMMIT_HOST} ${CODECOMMIT_USER} ${CODECOMMIT_PASSWORD}
fi