#!/bin/bash

if [ ! -x "$(command -v xcomposer)" ]; then
    echo "Composer is not installed.";
    exit 1;
fi

if [ ! -f "${COMPOSER_FOLDER}/composer.json" ]; then
    if [ ! -f "composer.json" ]; then
      echo "File composer.json not found in '${COMPOSER_FOLDER}'.";
      exit 1;
    fi
else
  cd "${COMPOSER_FOLDER}/" || exit
fi

xcomposer "$@"
