#!/bin/bash

if [ -n "$GITHUB_TOKEN" ]; then
    echo "Configurando github..."
    xcomposer config -g github-oauth.github.com ${GITHUB_TOKEN}
fi

if [ -n "$CODECOMMIT_USER" ]; then
    echo "Configurando codecommit..."
    xcomposer config -g http-basic.${CODECOMMIT_HOST} ${CODECOMMIT_USER} ${CODECOMMIT_PASSWORD}
fi