#!/bin/bash

source php-utils

if [ ! -x "$(command -v xcomposer)" ]; then
    echo "Composer is not installed.";
    exit 1;
fi

COMPOSER_JSON_HOME=$( get_composer_home )

cd "${COMPOSER_JSON_HOME}/"
xcomposer "$@"
