#!/bin/bash

echo "Configurando nome: ${PHP_NAME}";
sed -i '1d' ${PHP_FPM_CONFIG};
sed -i "1s/^/\[${PHP_NAME}\]\n/" ${PHP_FPM_CONFIG};

echo "Configurando PHP..."

if [ -n "${PHP_PM}" ]; then
	crudini --set ${PHP_FPM_CONFIG} ${PHP_NAME} pm ${PHP_PM};
fi;

if [ -n "${PHP_PM_MAX_CHILDREN}" ]; then
	crudini --set ${PHP_FPM_CONFIG} ${PHP_NAME} pm.max_children ${PHP_PM_MAX_CHILDREN};
fi;

if [ -n "${PHP_PM_START_SERVERS}" ]; then
	crudini --set ${PHP_FPM_CONFIG} ${PHP_NAME} pm.start_servers ${PHP_PM_START_SERVERS};
fi;

if [ -n "${PHP_PM_MIN_SPARE_SERVERS}" ]; then
	crudini --set ${PHP_FPM_CONFIG} ${PHP_NAME} pm.min_spare_servers ${PHP_PM_MIN_SPARE_SERVERS};
fi;

if [ -n "${PHP_PM_MAX_SPARE_SERVERS}" ]; then
	crudini --set ${PHP_FPM_CONFIG} ${PHP_NAME} pm.max_spare_servers ${PHP_PM_MAX_SPARE_SERVERS};
fi;

if [ -n "${PHP_PM_MAX_REQUESTS}" ]; then
	crudini --set ${PHP_FPM_CONFIG} ${PHP_NAME} pm.max_requests ${PHP_PM_MAX_REQUESTS};
fi;

if [ -n "${PHP_PM_PROCESS_IDLE_TIMEOUT}" ]; then
	crudini --set ${PHP_FPM_CONFIG} ${PHP_NAME} pm.process_idle_timeout ${PHP_PM_PROCESS_IDLE_TIMEOUT};
fi;

if [ "${SHOW_ERRORS}" = "true" ]; then
	echo "Configurando para mostrar erros..."
	crudini --set ${PHP_INI_CONFIG} "" display_errors "On";
fi;

if [ -n "${MEMORY_LIMIT}" ]; then
	echo "Alterando memoria limit para ${MEMORY_LIMIT}..."
	crudini --set ${PHP_INI_CONFIG} "" memory_limit ${MEMORY_LIMIT};
fi;

# PHP-FPM USER
if [ -n "$PHP_USER" ]; then
	echo "Configurando usuário..."
	sed -i "s/user=www-data/user=${PHP_USER}/g" ${PHP_FPM_CONFIG};
fi;

# PHP-FPM GROUP
if [ -n "$PHP_GROUP" ]; then
	echo "Configurando grupo..."
	sed -i "s/group=www-data/group=${PHP_GROUP}/g" ${PHP_FPM_CONFIG};
fi;

if [ -n "$XDEBUG" ] && [ "$XDEBUG" = "true" ]; then
	if [ ! -n "$XDEBUG_HOST" ]; then
		XDEBUG_HOST=host.docker.internal;
	fi;
	
	echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" >> ${CONFIG_XDEBUG}
	echo "xdebug.remote_enable=1" >> ${CONFIG_XDEBUG}
	echo "xdebug.remote_host=${XDEBUG_HOST}" >> ${CONFIG_XDEBUG}
	echo "xdebug.remote_handler=dbgp" >> ${CONFIG_XDEBUG}
	echo "xdebug.remote_log=/tmp/xdebug.log" >> ${CONFIG_XDEBUG}
	echo "xdebug.remote_autostart=on" >> ${CONFIG_XDEBUG}
	echo "xdebug.remote_connect_back=on" >> ${CONFIG_XDEBUG}

	if [ -n "$XDEBUG_IDEKEY" ]; then
		echo "xdebug.idekey=${XDEBUG_IDEKEY}" >> ${CONFIG_XDEBUG}
	else
		echo "xdebug.idekey=${PHP_NAME}" >> ${CONFIG_XDEBUG}
	fi

  	if [ -n "$XDEBUG_PROFILER" ]; then	
    	echo "xdebug.profiler_enable=1" >> ${CONFIG_XDEBUG};
		echo "xdebug.profiler_output_dir=${PATH_XDEBUG_PROFILE}" >> ${CONFIG_XDEBUG}
	fi;

	cat ${CONFIG_XDEBUG}
fi;

if [ -n "$OPCACHE" ]; then
	sed -i "s/opcache.validate_timestamps=1/opcache.validate_timestamps=0/g" ${PHP_INI_OPCACHE};
	cat ${PHP_INI_OPCACHE};
fi;

if [ -n "$OPCACHE_PRELOAD"]; then
	echo "opcache.preload=${OPCACHE_PRELOAD}" >> ${PHP_INI_OPCACHE}
	echo "opcache.preload_user=${PHP_USER:-www-data}" >> ${PHP_INI_OPCACHE}
fi

if [ -n "$PHP_SLOWLOG" ]; then
	echo "slowlog=/dev/stderr" >> ${PHP_FPM_CONFIG}
	echo "request_slowlog_timeout=5s" >> ${PHP_FPM_CONFIG}
fi;

cat ${PHP_FPM_CONFIG};