#!/bin/bash
set -e

if [ "${CLI}" = "false" ]; then
    if [ -n "${1}" ] && [ "${1}" != "php-fpm" ]; then
        set -- "$@" && start-php-fpm
    else
        set -- start-php-fpm
    fi
fi

start

exec "$@"