#!/bin/bash
echo "Executando command '$@'...";
COMMAND_FILE="${PUBLIC_HTML}/cmd-file.sh"
touch ${COMMAND_FILE}
echo "#!/bin/bash" >> ${COMMAND_FILE};
echo "$@" >> ${COMMAND_FILE}
chmod +x ${COMMAND_FILE}
${COMMAND_FILE}
rm -f ${COMMAND_FILE}