#!/bin/bash

apt update && apt install -y git unzip
rm -rf /var/lib/apt/lists/*

export COMPOSER_ALLOW_SUPERUSER=1

curl -sS https://getcomposer.org/installer | \
 php -- --install-dir=/usr/local/bin --filename=xcomposer

xcomposer global require hirak/prestissimo dg/composer-cleaner