#!/bin/bash

sudo apt update && sudo apt install -y git unzip
sudo rm -rf /var/lib/apt/lists/*

export COMPOSER_HOME=/etc/composer
export COMPOSER_ALLOW_SUPERUSER=1

sudo curl -sS https://getcomposer.org/installer | \
sudo php -- --install-dir=/usr/local/bin --filename=composer