#!/bin/bash

source php-utils

COMPOSER_JSON_HOME=$( get_composer_home )
cd "${COMPOSER_JSON_HOME}/"

if [ -f vendor/bin/phinx ]; then
  php vendor/bin/phinx migrate -vvv;
fi;

if [ -f artisan ]; then
  php artisan migrate;
fi;

run-event "db-migrated"