#!/bin/bash

source composer-util

COMPOSER_JSON_HOME=$( get_composer_home )
cd "${COMPOSER_JSON_HOME}/"

if [ -f vendor/bin/phinx ]; then
  vendor/bin/phinx migrate -vvv;
fi;

if [ -f artisan ]; then
  php artisan migrate;
fi;