#!/bin/bash

run-event "db-ready"

if [ -n "$DB_MIGRATE" ] && [ "$DB_MIGRATE" = "true" ]; then
    migrate-db
fi 

if [ -n "$DB_SEED" ] && [ "$DB_SEED" = "true" ]; then
    seed-db
fi 

if [ "${CLI}" = "false" ] && [ -n "${1}" ] && [ "${1}" != "php-fpm" ]; then
    exec-cmd "$@"
    PHP_FPM_PARAMS="php-fpm"
else
    PHP_FPM_PARAMS="$@"
fi

run-event "ready"

if [ "${CLI}" = "false" ]; then
    set -- start-php-fpm "${PHP_FPM_PARAMS}"
fi

exec "$@"