#!/bin/bash

configure-php;

if [ -n "$INSTALL_COMPOSER" ]; then
    install-composer
    composer-config
fi

if [ -n "$COMPOSER_INSTALL" ]; then
    composer-install ${COMPOSER_INSTALL_PARAMS}
fi

if [ -n "$DB_HOST" ]; then
    echo "Aguardando banco de dados... ${DB_HOST}:${DB_PORT}";

	dockerize \
		-wait tcp://${DB_HOST}:${DB_PORT} \
		-timeout 30s \
	    start-php "$@"
else
	start-php "$@"
fi