#!/bin/bash

if [ ! -f "${COMPOSER_FOLDER}/composer.json" ]; then
  COMPOSER_FOLDER=${WWW}
fi

echo "COMPOSER_FOLDER: ${COMPOSER_FOLDER}"
export ${COMPOSER_FOLDER}

configure-php

if [ -n "$INSTALL_COMPOSER" ]; then
  install-composer
fi

if [ -x "$(command -v xcomposer)" ]; then
	composer-config
fi

if [ -n "$COMPOSER_INSTALL" ]; then
  composer-install ${COMPOSER_INSTALL_PARAMS}
fi

if [ -n "$DB_HOST" ]; then
    echo "Aguardando banco de dados... ${DB_HOST}:${DB_PORT}";

	dockerize \
		-wait tcp://${DB_HOST}:${DB_PORT} \
		-timeout 30s \
	    start-php "$@"
else
	start-php "$@"
fi