#!/bin/bash

if [ -n "$DB_MIGRATE" ]; then
    migrate-db
fi 

if [ -n "${1}" ]; then
    echo "Executando command...";
    exec-cmd "$@"
fi

echo "Iniciando PHP...";
/usr/bin/supervisord -n -c ${PHP_CONFIG_PATH}supervisor.conf;